### ISSUE TITLE
Enabling HDMI audio output

### ISSUE THREAD

**Issue by pcarranzav** [resin-os/resin-up-board#51]
https://wiki.up-community.org/Audio suggests changes may be needed at the BIOS level? But we should also ensure resinOS supports it.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_c6kj)

**Comment by floion** [comment]
Fixed by https://github.com/resin-os/resin-up-board/pull/52
